name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - staging
      - main

jobs:
  build:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        working-directory: ./my-react-app
        run: npm install

      # Step 4: SonarQube Code Analysis
      - name: SonarQube Code Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: ./my-react-app
          args: >
            -Dsonar.organization=my-org
            -Dsonar.projectKey=my-Java-web-app
            -Dsonar.sources=src
            -Dsonar.exclusions=**/target/**,**/test/**,**/node_modules/**,**/*.class
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        working-directory: ./my-react-app
        run: npm install

      # Step 3: Build Application
      - name: Build React Application
        working-directory: ./my-react-app
        run: npm run build

      # Step 4: Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./my-react-app/build
          production-deploy: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        working-directory: ./my-react-app
        run: npm install

      # Step 3: Build Application
      - name: Build React Application
        working-directory: ./my-react-app
        run: npm run build

      # Step 4: Deploy to Netlify
      - name: Deploy to Staging on Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./my-react-app/build
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.STAGING_NETLIFY_SITE_ID }}
