name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - main
      - staging
env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        working-directory: ./my-react-app
        run: npm install

      # Step 4: Run SonarCloud Analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./my-react-app
        env:
          SONAR_TOKEN: c6c9f2e21569fcd43d5b9d94f3462232a55f13f3
          SONAR_ORGANIZATION: biegemedusa446
          SONAR_PROJECT_KEY: Biegemedusa446_CI-CD-Pipeline-For-Static-React-Web-App
          SONAR_SCANNER_EXTRA_ARGS: >
            -Dsonar.sources=src
            -Dsonar.exclusions=**/node_modules/**,**/*.test.js,**/build/**
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

      # Step 5: Build React App
      - name: Build React Application
        working-directory: ./my-react-app
        run: npm run build

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        working-directory: ./my-react-app
        run: npm install
      
      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g

      # Step 3: Deploy to Netlify
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
         prod_flag=""
         if [ "$BRANCH_NAME" = "main" ]; then prod_flag="--prod"; fi
         netlify deploy \
           --dir dist \
           --site ${{ secrets.PRODUCTION_NETLIFY_SITE_ID }} \
           --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
           $prod_flag      
