name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - development
      - staging
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 3: Run Tests
    - name: Run Tests
      run: npm test -- --watchAll=false

    # Step 4: Run SonarQube Analysis
    - name: Run SonarQube Analysis
      env:
        SONAR_HOST_URL: http://localhost:9000
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=Automated-Static-Website-Deployment-Using-React-and-GitHub-Actions \
          -Dsonar.sources=src \
          -Dsonar.exclusions=**/node_modules/**,**/*.test.js,**/build/** \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN

    # Step 5: Trivy Dependency Scanning
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: node:16 # Replace with your Node.js version

  deploy-production:
    name: Deploy to Production on Netlify
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 3: Build Application
    - name: Build React Application
      env:
        REACT_APP_ENV: production
      run: npm run build

    # Step 4: Deploy to Netlify (Production)
    - name: Deploy to Netlify
      uses: netlify/actions/deploy@v1.1.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.PRODUCTION_NETLIFY_SITE_ID }}
        BUILD_DIR: ./build

  deploy-staging:
    name: Deploy to Staging on Netlify
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 3: Build Application
    - name: Build React Application
      env:
        REACT_APP_ENV: staging
      run: npm run build

    # Step 4: Deploy to Netlify (Staging)
    - name: Deploy to Netlify
      uses: netlify/actions/deploy@v1.1.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.STAGING_NETLIFY_SITE_ID }}
        BUILD_DIR: ./build
